### ISSUE TITLE
cannot patch DM-v57_w_M31

### ISSUE THREAD

**Issue by nhnguyen98** [a-e-egorov/GALPROP_DM#1]
I am trying to do patch -i DM-v57_w_M31.patch. However I received the message 
"patching file B_field_3D_model.cc
Reversed (or previously applied) patch detected!  Assume -R? [n] n
Apply anyway? [n] n
Skipping patch."
It happen to other file too. Please let me know what should I do.
Thank you.

**Comment by a-e-egorov** [comment]
I resolved this issue and updated "DM-v57_w_M31.patch" file respectively.
